"""A-2: the robustness table + error-analysis note the briefing deck (slide 16)
rewards directly. Regenerates from the JSON/CSV an `evaluate` run already
writes, so it stays current every iteration.

    python -m detector.error_report <name:run_dir> [<name:run_dir> ...] --out ERROR_ANALYSIS.md

Optionally writes an FP/FN contact sheet per run dir with --montage.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def _rows(run_dir: Path) -> list[dict]:
    with (run_dir / "metrics.csv").open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _f(v) -> float:
    return float(v) if v not in (None, "") else float("nan")


def _condition_table(rows: list[dict]) -> list[str]:
    out = ["| condition | acc | ROC-AUC | FPR | FNR |", "|---|---|---|---|---|"]
    for r in rows:
        flag = "" if (_f(r["fpr"]) <= 0.03 and _f(r["fnr"]) <= 0.03) else " ⚠"
        out.append(
            f"| {r['condition']} | {_f(r['accuracy']):.3f} | {_f(r['roc_auc']):.4f} "
            f"| {_f(r['fpr']):.4f} | {_f(r['fnr']):.4f}{flag} |"
        )
    return out


def _representative(run_dir: Path, kind: str, k: int = 6) -> list[dict]:
    path = run_dir / "errors.csv"
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as fh:
        errs = [e for e in csv.DictReader(fh) if e["error_type"] == kind]
    # highest-confidence mistakes first, dedup by image
    seen, out = set(), []
    for e in sorted(errs, key=lambda e: -float(e["confidence"])):
        if e["image_path"] in seen:
            continue
        seen.add(e["image_path"])
        out.append(e)
        if len(out) >= k:
            break
    return out


def _montage(run_dir: Path, name: str, errs: list[dict], kind: str) -> str | None:
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        return None
    if not errs:
        return None
    cell, cols = 200, min(len(errs), 6)
    rows = (len(errs) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * cell, rows * (cell + 22)), "white")
    draw = ImageDraw.Draw(sheet)
    for i, e in enumerate(errs):
        try:
            im = Image.open(e["image_path"]).convert("RGB")
        except Exception:
            continue
        im.thumbnail((cell, cell))
        x, y = (i % cols) * cell, (i // cols) * (cell + 22)
        sheet.paste(im, (x, y))
        draw.text((x + 3, y + cell + 3),
                  f"P(AI)={float(e['probability_ai']):.3f}  {e['condition']}",
                  fill="black")
    dest = run_dir / f"errors_{kind}.png"
    sheet.save(dest)
    return str(dest)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("runs", nargs="+", help="name:run_dir")
    ap.add_argument("--out", default="ERROR_ANALYSIS.md")
    ap.add_argument("--montage", action="store_true")
    args = ap.parse_args()

    doc: list[str] = [
        "# Robustness & error analysis",
        "",
        "_Regenerated by `python -m detector.error_report`. `⚠` marks a condition "
        "outside the ±3% FPR/FNR target._",
        "",
        "## Headline",
        "",
        "| eval set | Final Score | clean ROC-AUC | robust ROC-AUC | clean FPR | clean FNR | conds ≤3% |",
        "|---|---|---|---|---|---|---|",
    ]
    per_run = []
    for spec in args.runs:
        name, d = spec.split(":", 1)
        run_dir = Path(d)
        summary = json.loads((run_dir / "summary.json").read_text(encoding="utf-8"))
        rows = _rows(run_dir)
        clean = summary["clean"]
        robust = summary["robust_mean"]
        final = 0.5 * _f(clean["roc_auc"]) + 0.5 * _f(robust["roc_auc"])
        within = sum(1 for r in rows if _f(r["fpr"]) <= 0.03 and _f(r["fnr"]) <= 0.03)
        doc.append(
            f"| {name} | {final:.4f} | {_f(clean['roc_auc']):.4f} | {_f(robust['roc_auc']):.4f} "
            f"| {_f(clean['fpr']):.4f} | {_f(clean['fnr']):.4f} | {within}/{len(rows)} |"
        )
        per_run.append((name, run_dir, summary, rows))

    for name, run_dir, summary, rows in per_run:
        doc += ["", f"## {name}", "",
                f"threshold {summary.get('threshold')} · {summary['images']} images", ""]
        doc += _condition_table(rows)
        for kind, title in (("FP", "False positives — real images called AI"),
                            ("FN", "False negatives — AI images called real")):
            errs = _representative(run_dir, kind)
            if not errs:
                continue
            doc += ["", f"### {title}", ""]
            for e in errs:
                doc.append(
                    f"- `{Path(e['image_path']).name}` — P(AI)={float(e['probability_ai']):.3f}, "
                    f"condition `{e['condition']}`"
                )
            if args.montage:
                m = _montage(run_dir, name, errs, kind)
                if m:
                    doc.append(f"\n![{kind}]({Path(m).name})")

    Path(args.out).write_text("\n".join(doc) + "\n", encoding="utf-8")
    print(f"[error_report] wrote {Path(args.out).resolve()}")
    preview = "\n".join(doc[:14]).encode("ascii", "replace").decode()
    print(preview)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
